=head1 NAME

Business::Shipping - Shipping cost calculator for UPS and USPS

=head1 INSTALLATION

 perl Makefile.PL
 make
 make test
 make install

=head1 DEPENDENCIES

 Bundle::LWP 
 Crypt::SSLeay
 XML::Simple
 XML::DOM
 Digest::SHA1
 Error
 Cache::FileCache
 Data::Dumper
 
=head1 USAGE

 * To use USPS interface, you must first sign up online (for free).
 	- http://www.uspsonlinetools.com
    
 * Sign up for UPS:
	You will also need to get a User Id, Password, and Access Key from UPS.
	 
	 * Read about it online:
	 
	http://www.ec.ups.com/ecommerce/gettools/gtools_intro.html 
	 
	 * US Sign up here:
	 
	https://www.ups.com/servlet/registration?loc=en_US_EC
	 
 * See Shipping.pm POD documentation for API notes.

=head1 EXAMPLES

This module is used by the Interchange E-Commerce software 
(http://www.icdevgroup.org).  For a reference implementation of Business::Shipping,
see the doc/xps-query.tag file, it implements a function that takes 
shipping-related arguments, builds a Business::Shipping object, then returns the 
calculatd cost.
 
=head1 WEBSITE
 
 http://www.kavod.com/Business-Shipping
 
The website will carry the most recent version, as well as instructions for
accessing the anonymous CVS repository. 

=head1 COPYRIGHT AND LICENCE

Copyright (c) 2003 Kavod Technologies, Dan Browning. All rights reserved. 
This program is free software; you can redistribute it and/or modify it 
under the same terms as Perl itself.

=head1 AUTHOR

	Dan Browning
	Kavod Technologies
	<db@kavod.com>
	http://www.kavod.com

=head1 CREDITS

 * Kevin Old <kold@carolina.rr.com> got the USPS XML generator working.
 * sauoq on PerlMonks.org provided valuable commentary and ideas. 

=cut
