=head1 NAME

Business::Shipping - Shipping cost calculator for UPS and USPS

=head1 INSTALLATION

 perl Makefile.PL
 make
 make test
 make install

=head1 DEPENDENCIES

 Bundle::LWP 
 Crypt::SSLeay
 XML::Simple
 XML::DOM
 Digest::SHA1
 Error
 Cache::FileCache
 Data::Dumper
 Class::MethodMaker
 
=head1 USAGE

 * See Shipping.pm POD documentation for API and usage examples.
 
 * For USPS: Sign up online for free:
 
 	- http://www.uspsonlinetools.com
    
 * For UPS: Sign up online for free:
 
	- https://www.ups.com/servlet/registration?loc=en_US_EC

	You will get a User Id, Password, and Access Key from UPS. 

=head1 EXAMPLES

This module is used by the Interchange E-Commerce software 
(http://www.icdevgroup.org).  For a reference implementation of Business::Shipping,
see the UserTag/business-shipping.tag file, it implements a function that takes 
shipping-related arguments, builds a Business::Shipping object, then returns the 
calculatd cost.
 
=head1 WEBSITE
 
 http://www.kavod.com/Business-Shipping
 
The website carries the most recent version, as well as instructions for
accessing the anonymous CVS repository. 

=head1 COPYRIGHT AND LICENCE

Copyright (c) 2003 Kavod Technologies, Dan Browning. All rights reserved. 
Licensed under the GNU Public Licnese (GPL).  See COPYING for more info.

=head1 AUTHOR

	Dan Browning
	Kavod Technologies
	<db@kavod.com>
	http://www.kavod.com

=head1 CREDITS

 * Kevin Old <kold@carolina.rr.com> got the USPS XML generator working.
 * sauoq on PerlMonks.org provided valuable commentary and ideas. 
 * bbfu on PerlMonks.org got Class::MethodMaker working with SUPER. 

=cut
