# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-Shipping-DataTools
version:      1.01
version_from: lib/Business/Shipping/DataTools.pm
installdirs:  site
requires:
    Archive::Zip:                  0
    Business::Shipping:            1.92
    Business::Shipping::DataFiles: 1
    Config::IniFiles:              0
    Storable:                      0
    Test::More:                    0
    Text::CSV::Simple:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
