# http://module-build.sourceforge.net/META-spec.html
name:         Business-Shipping
version:      1.90
version_from: lib/Business/Shipping.pm
installdirs:  site
requires:
    Class::MethodMaker::Engine:    0
    Log::Log4perl:                 0
    Scalar::Util:                  0
    Test::More:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
