# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-Shipping
version:      1.07
version_from: 
installdirs:  site
requires:
    Archive::Zip:                  0
    Bundle::DBD::CSV:              0
    Cache::FileCache:              0
    Class::MethodMaker:            < 2.0
    Clone:                         0
    Config::IniFiles:              0
    Crypt::SSLeay:                 0
    Data::Dumper:                  0
    Devel::Required:               0.03
    Error:                         0
    Getopt::Mixed:                 0
    LWP::UserAgent:                0
    Math::BaseCnv:                 0
    Scalar::Util:                  1.10
    XML::DOM:                      0
    XML::Simple:                   2.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
