--- #YAML:1.0
name:         Business-Shipping
version:      1.54
author:
  - Dan Browning, db@kavod.com
abstract: Rates and tracking for UPS and USPS
installdirs:  site
requires:
    Class::MethodMaker::Engine: 0
    Log::Log4perl:              0
    Scalar::Util                1.10
distribution_type: module
generated_by: Module::Build version 0.25_03
